### ISSUE TITLE
Gcloud service account

### ISSUE THREAD

**Issue by theallseingeye** [estafette/estafette-gke-preemptible-killer#10]
Does this require a gcloud service account key to be created like  https://github.com/estafette/estafette-gke-node-pool-shifter ?

**Comment by etiennetremel** [comment]
Yes it does, we need to adjust the documentation for that.

**Comment by theallseingeye** [comment]
Could you give some tips on how to do this?

**Comment by etiennetremel** [comment]
@theallseingeye I added instructions on how to create the Google Service Account, you can check the linked PR. And before it get merged into master, you can test it by checking out the _add-service-account-instructions_ branch.
