### ISSUE TITLE
Error creating compute client

### ISSUE THREAD

**Issue by smk508** [estafette/estafette-gke-preemptible-killer#19]
Hi,
I've installed the preemptible-killer following the instructions, including setting up a service account and including that in the vales.yaml when installing the chart. However, I get this error where it's unable to read the environment variable for the service account file. Any idea what causes this?

Thanks.

![image](https://user-images.githubusercontent.com/13842719/56009683-a68f8800-5cae-11e9-9b95-99e2e1650148.png)

**Comment by etiennetremel** [comment]
From the error message provided, it seems that there is a syntax error in the json you provided, can you double check?

**Comment by smk508** [comment]
I figured it out, thanks. I incorrectly specified the path to the credentials json. I didn't prefix my path with ./, and adding that fixed the problem.
