### ISSUE TITLE
Github/Helm chart versioning

### ISSUE THREAD

**Issue by aelbarkani** [estafette/estafette-gke-preemptible-killer#33]
Hi,

First of all, many thanks for this awesome component.

Would be possible to version the releases with tags in Github ? Otherwise it is difficult to deploy a specific chart version.

Thanks !

**Comment by cagataygurturk** [comment]
+1 for this please

**Comment by JorritSalverda** [comment]
I'm working on setting up helm charts at https://helm.estafette.io/. For each build a pre-release package will be pushed there and when making an actual release a _release_ package will be pushed there. At the same time I want to create a Github release and if a milestone with the same version exists use it for its release notes. Hope to have this operational over the next weeks.

**Comment by JorritSalverda** [comment]
Releasing version 1.2.0 in a minute, it has new instructions on how to use the helm chart from the new official repo.

**Comment by aelbarkani** [comment]
excellent, thank you very much !
