### ISSUE TITLE
Question: How to select the node pool?

### ISSUE THREAD

**Issue by bappr** [estafette/estafette-gke-preemptible-killer#38]
Hey guys,

Thanks for your work, very helpful.
I am very new to your preemptible-killer, I have been using [Spotinst](https://spotinst.com) until now but wondering if I cannot do something on my own.

Here are 2 questions:
- How can I select the node pool I want the killer to work on (assuming I have more than 1 preemptible node pool)?
- Does the killer guarantee that 2 nodes can never be down at the same time? What if the killing of a node is due to a system event?

Thanks a lot.

**Comment by nvtkaszpir** [comment]
1. selecting node pool is not supported yet, the code is processing ALL preemptible nodes attached to the cluster, and there is no way to limit it even via taints or annotations
2. no, ensure your have PDB and enough of replicas, so for better safety just use non-preemptible nodes in different zones

**Comment by bappr** [comment]
OK well noted.
Thanks for the clear answer. :)

**Comment by mykhailosmolynets** [comment]
it seems that random termination fixed using labels, isn't it? https://github.com/estafette/estafette-gke-preemptible-killer/pull/40
