### ISSUE TITLE
Incomplete Documentation

### ISSUE THREAD

**Issue by EntrepreneurAJ** [estafette/estafette-gke-preemptible-killer#52]
After the changes to the newer Helm repo, when I install fresh it always gives a 403 error when following the readme file.

Pre private helm repo there used to be a flag to show where the Google Service Account JSON Key was this seems to be no more as a result HTTP 403 Forbidden is being received from the Kubernetes API.

**Comment by phroggyy** [comment]
Same. It appears that the cluster role is missing permissions to access nodes

**Comment by JorritSalverda** [comment]
The `ClusterRole` will be fixed in milestone `1.2.3` via https://github.com/estafette/estafette-gke-preemptible-killer/pull/57
