### ISSUE TITLE
Error deleting GCloud instance

### ISSUE THREAD

**Issue by donifer** [estafette/estafette-gke-preemptible-killer#61]
I'm pretty confident this is a user error but I'm getting this log and the instance can't be deleted.

```
<nil> ERR Error deleting GCloud instance error="Delete https://www.googleapis.com/compute/v1/projects/<redacted-project-id>/zones/us-central1-a/instances/<redacted-instancee-id>?alt=json: private key should be a PEM or plain PKSC1 or PKCS8; parse error: asn1: syntax error: sequence truncated" host=<redacted-host>
```

What I did:
- Followed the readme section for "Create a Google Service Account"
- Deployed with helm following the instructions, but using a different name `preembtible-killer` (I don't think it matters).

What am I missing? 🤔

**Comment by donifer** [comment]
I _believe_ I needed to add the name `preemptible-killer` since thats the SA name it gets created when following the README.

```yaml
serviceAccount:
  create: true
  name: preemptible-killer
```

Not sure if that is actually the issue, seems like I need to wait 12 hours and find out, unless there is a way I can force `preemptible-killer` to try and delete the instances before that.

**Comment by donifer** [comment]
Update: Got the same error, I must be missing something else.

**Comment by donifer** [comment]
I'm just dumb, need to either add the key as part of the secrets section in values.yaml or use the service account controller. Apologies.

**Comment by Jhooow93** [comment]
I'm got the same error.
Can you please teach me what you do to solve this ?
