### ISSUE TITLE
private key should be a PEM or plain PKSC1 or PKCS8

### ISSUE THREAD

**Issue by Jhooow93** [estafette/estafette-gke-preemptible-killer#74]
Hi,

I'm pretty confident this is a user error but I'm getting this log and the instance can't be deleted.

`<nil> ERR Error deleting GCloud instance error="Delete https://www.googleapis.com/compute/v1/projects/<project>/zones/us-east4-a/instances/gke-customer-services-t0-c7ef-gateway-6766c062-7pbx?alt=json: private key should be a PEM or plain PKSC1 or PKCS8; parse error: asn1: syntax error: sequence truncated" host=gke-customer-services-t0-c7ef-gateway-6766c062-7pbx`

I got the same error on estafette shifter too.
I'm doing something wrong ?

**Comment by Jhooow93** [comment]
Documentation is wrong.
You need to set --set-file secret.googleServiceAccountKeyfileJson=google_service_account.json on deployment.

**Comment by ashishjh-bst** [comment]
@Jhooow93 I am facing the same issue, what was the fix for it?
